CREATE TABLE Users (
  UserId INT IDENTITY(1,1) NOT NULL,
  Username NVARCHAR(255) NOT NULL,
  Password NVARCHAR(255) NOT NULL,
  Email NVARCHAR(255) NOT NULL,
  FullName NVARCHAR(255) NULL,
  CreatedAt DATETIME NULL,
  PRIMARY KEY (UserId)
);
